# Generated by Django 5.2.13 on 2026-04-17 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ai_ml_assistant', '0002_useraccount_delete_searchhistory'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserAccount',
        ),
    ]
